name: Docker Action Demo
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./.github/workflows/actions/docker-action
        id: hello
        with:
          who-to-greet: 'Foysal Ahmed'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
